class Solution:
    def kthCharacter(self, k: int) -> str:
        """Returns the k-th character in the infinite string generated by the following process:

        - Start with word = "a".
        - Repeatedly perform the operation:
            * For each character in the current word, change it to its next character in the English alphabet (with 'z' cycling to 'a').
            * Append the resulting string to the end of the current word.

        The process continues until the word has at least k characters.

        Args:
            k (int): The 1-based index of the character to retrieve.

        Returns:
            str: The k-th character in the generated string.

        Example:
            >>> kthCharacter(1)
            'a'
            >>> kthCharacter(2)
            'b'

        LeetCode: Beats 100% of submissions
        """
        word = "ab"
        temp = "b"

        while len(word) < k:
            for i in range(len(word) - len(temp), len(word)):
                temp += chr(ord(word[i]) + 1)

            word += temp

        return word[k - 1]
